// SPDX-License-Identifier: GPL-3.0-or-later
export default {
"Strength:": "棋力：",
".": "。",
"Promote on {sq}": "在 {sq} 升變",
"queen": "皇后",
"rook": "城堡",
"bishop": "主教",
"knight": "騎士",
"rejected: {msg}": "已拒絕：{msg}",
"No moves yet. Fly moves are shown in gold.": "尚無棋步。果蠅的棋步以金色顯示。",
"No moves yet. Black moves first; fly moves are shown in gold.": "尚無棋步。黑方先下；果蠅的棋步以金色顯示。",
"FLY": "果蠅",
"YOU": "你",
"White wins": "白方勝",
"Black wins": "黑方勝",
"Draw": "和局",
"You win": "你贏了",
"The fly wins": "果蠅贏了",
"Black {b} : {w} White": "黑 {b} : {w} 白",
"checkmate": "將死",
"stalemate": "逼和",
"insufficient material": "子力不足",
"fifty moves": "五十步規則",
"threefold repetition": "三次重複局面",
"White to move": "輪到白方",
"Black to move": "輪到黑方",
"your turn": "換你下",
"the fly is thinking…": "果蠅思考中…",
"the fly is up": "輪到果蠅",
"check": "將軍",
"Game over — <b>{reason}</b> ({result}). Press <b>New game</b> to play again.": "棋局結束：<b>{reason}</b>（{result}）。按<b>新棋局</b>再下一盤。",
"Game over — <b>{who}</b> ({score}). Press <b>New game</b> to play again.": "棋局結束：<b>{who}</b>（{score}）。按<b>新棋局</b>再下一盤。",
"cannot start the engine: {msg}": "無法啟動引擎：{msg}",
"you have no legal move — passing": "你沒有合法的落子處，自動跳過",
"pass": "跳過",
"Mushroom Body": "蘑菇體",
"Central Complex": "中央複合體",
"Antennal Lobe": "觸角葉",
"Strength: {s}": "棋力：{s}",
"not measured yet (partially trained)": "尚未量測（只經過部分訓練）",
"not measured yet": "尚未量測",
"weights location not configured": "尚未設定權重位置",
"This browser cannot keep downloaded brains; each visit downloads again.": "這個瀏覽器無法保存已下載的腦，每次造訪都會重新下載。",
"Stored in this browser: {mb} MB ({list}).": "已存在這個瀏覽器中：{mb} MB（{list}）。",
"Downloaded brains are kept in this browser, so each one downloads only once.": "下載過的腦會保存在這個瀏覽器中，每個腦只需要下載一次。",
"Downloaded ✓ (loads instantly)": "已下載 ✓（可立即載入）",
"Download {mb} MB": "下載 {mb} MB",
"Brain atlas": "腦圖譜",
"Choose a fly brain to see its real traced neurons here; they light up as the circuit plays.": "選擇一個果蠅腦後，這裡會顯示它真實追蹤重建的神經元；迴路下棋時它們會亮起。",
"Every move is computed by a spiking network wired from a <b>real fruit fly brain circuit</b> in the MaleCNS connectome, with trained synaptic weights. Choose which circuit you play against: the mushroom body, the antennal lobe or the central complex. The whole network runs <b>in your browser</b> (a Web Worker) — no server computes anything.": "每一步棋都由一個脈衝神經網路計算，它依 MaleCNS 連結體中的一段<b>真實果蠅腦迴路</b>接線，並使用訓練過的突觸權重。請選擇你要對弈的迴路：蘑菇體、觸角葉或中央複合體。整個網路都<b>在你的瀏覽器中</b>執行（Web Worker），沒有任何伺服器參與運算。",
"Choose your opponent": "選擇你的對手",
"— pick a fly brain to start": "— 選一個果蠅腦開始",
"Could not load {name}: {msg}": "無法載入{name}：{msg}",
"mushroom-body": "蘑菇體",
"mushroom body": "蘑菇體",
"Every move is computed by a spiking network wired from the <b>real MaleCNS {name} connectome</b> — {H} measured neurons, {E} neuron-to-neuron connections, excitatory/inhibitory signs from neurotransmitter annotations. On the right, those neurons are drawn at their <b>real measured soma positions</b> and light up as the circuit runs. The network's state is <b>never reset</b>: it carries forward from move to move, so what you see at move 40 descends from move 1. The whole network runs <b>in your browser</b> (a Web Worker) — no server computes anything.": "每一步棋都由一個脈衝神經網路計算，它依<b>真實的 MaleCNS {name}連結體</b>接線：{H} 個實測神經元、{E} 條神經元之間的連結，興奮／抑制符號取自神經傳導物質標註。右側把這些神經元畫在它們<b>真實量測到的細胞體位置</b>，並隨著迴路運作而亮起。網路狀態<b>從不重設</b>：它一步一步延續下去，所以你在第 40 步看到的活動，是從第 1 步一路延續而來。整個網路都<b>在你的瀏覽器中</b>執行（Web Worker），沒有任何伺服器參與運算。",
"loading the {name}…": "正在載入{name}…",
"{n} UCI tokens": "{n} 個 UCI 棋步記號",
"{n} tokens (64 squares, pass, start and end markers)": "{n} 個記號（64 個格子、跳過、開始與結束標記）",
"There is no search and no evaluation function: each move is one timestep of the network, restricted to legal moves by chess.js. The interesting claim is <i>which substrate is computing</i>.": "這裡沒有搜尋，也沒有評估函數：每一步棋都只是網路的一個時間步，並由 chess.js 限制在合法棋步之內。真正有意思的是<i>究竟是什麼基質在計算</i>。",
"There is no search and no evaluation function: each move is one timestep of the network, restricted to legal squares. The interesting claim is <i>which substrate is computing</i>.": "這裡沒有搜尋，也沒有評估函數：每一步棋都只是網路的一個時間步，並限制在合法落子格之內。真正有意思的是<i>究竟是什麼基質在計算</i>。",
"<b>Honest caveat.</b> This {name} model is only partially trained and plays far weaker than the mushroom body.": "<b>老實說明。</b>這個{name}模型只經過部分訓練，棋力遠弱於蘑菇體。",
"Its strength has not been measured yet.": "它的棋力尚未量測。",
"<b>Honest caveat.</b> This is not a strong engine, and the strength of this model has not been measured yet. Every move is restricted to legal moves by chess.js. The interesting claim is <i>which substrate is computing</i>.": "<b>老實說明。</b>這不是一個強大的棋類引擎，而且這個模型的棋力尚未量測。每一步棋都由 chess.js 限制在合法棋步之內。真正有意思的是<i>究竟是什麼基質在計算</i>。",
"<b>Honest caveat.</b> This is not a strong engine: {elo}{prev}. On {test} it picks Stockfish's best move <b>{sf}</b> of the time (opening {op}, early middlegame {em}, middlegame {mg}, endgame {eg}) and the move the human played {hm}.": "<b>老實說明。</b>這不是一個強大的棋類引擎：{elo}{prev}。在{test}上，它有 <b>{sf}</b> 的時候選到 Stockfish 的最佳棋步（開局 {op}、中局前段 {em}、中局 {mg}、殘局 {eg}），與人類實際下的棋步一致的比例為 {hm}。",
"({x})": "（{x}）",
"{elo} · Stockfish best-move agreement {sf} · human move-match {hm}": "{elo}・與 Stockfish 最佳棋步一致 {sf}・與人類棋步一致 {hm}",
"<b>Honest caveat.</b> This is not a strong engine, and the strength of this model has not been measured yet.": "<b>老實說明。</b>這不是一個強大的棋類引擎，而且這個模型的棋力尚未量測。",
"<b>Honest caveat.</b> This is not a strong engine.": "<b>老實說明。</b>這不是一個強大的棋類引擎。",
"Matches: {m}.": "對戰設定：{m}。",
"learning & memory: pattern → value": "學習與記憶：模式 → 價值",
"legend|Kenyon cell": "Kenyon cell（KC）",
"legend|MBON": "MBON（輸出神經元）",
"legend|DAN": "DAN（多巴胺神經元）",
"legend|APL": "APL 神經元",
"legend|other MB": "其他蘑菇體神經元",
"class|other": "其他",
"class|all": "全部",
"class|receptor": "受器",
"ring and extrinsic ring neurons (input)": "環狀與外環狀神經元（輸入）",
"PFN columnar neurons (input)": "PFN 柱狀神經元（輸入）",
"PFL steering output neurons (readout)": "PFL 轉向輸出神經元（讀出）",
"other central-complex neurons": "其他中央複合體神經元",
"olfactory, thermo- and hygrosensory receptor neurons (input)": "嗅覺、溫覺與濕覺受器神經元（輸入）",
"projection neurons (readout)": "投射神經元（讀出）",
"local and inter-neurons": "局部神經元與中間神經元",
"ER ring (landmark/visual) + PFN (self-motion via NO) + ExR": "ER 環狀神經元（地標／視覺）＋ PFN（經由小結的自身運動）＋ ExR",
"PFL1/2/3 (steering -> LAL)": "PFL1/2/3（轉向 → 側副葉）",
"ORN/TRN/HRN receptor neurons": "ORN/TRN/HRN 受器神經元",
"ALPN+ALON projection neurons": "ALPN＋ALON 投射神經元",
"Dopamine gate — the write": "多巴胺閘門：寫入",
"{n}of {total} DANs spiking this timestep": "{n} 個 DAN 在這個時間步發放脈衝（共 {total} 個）",
"gate × fast-weight write": "閘門 × 快速權重寫入",
"When DANs spike they multiplicatively gate the KC→MBON current and drive the fast-weight write — the fly's real three-factor plasticity rule, running inside the game.": "DAN 發放脈衝時，會以乘法方式調控 KC→MBON 的電流，並驅動快速權重的寫入：這是果蠅真實的三因子可塑性規則，就在棋局中運作。",
"KC stays <b>sparse</b> — that is the point of an expansion layer, and APL's global inhibition is what enforces it. MBON is a small population so its rate is coarse; APL is one neuron per hemisphere, so it reads 0%, 50% or 100%.": "KC 的活動保持<b>稀疏</b>：這正是擴展層的用意，而 APL 的全域抑制負責維持這種稀疏。MBON 的數量少，所以發放率的刻度較粗；APL 每側只有一個神經元，所以只會是 0%、50% 或 100%。",
"Hemispheres": "左右半腦",
"The connectome is bilateral, with edges crossing the midline in both directions.": "連結體左右對稱，並有雙向跨越中線的連結。",
"cross-midline edges": "跨中線連結",
"R→L / L→R": "右→左／左→右",
"measured, not modelled": "實測資料，並非模型推估",
"{name} atlas": "{name}圖譜",
"Mushroom body": "蘑菇體",
"measured soma coordinates": "實測細胞體座標",
"Frontal view": "正面",
"Dorsal view": "背面",
"Memory overlay: on": "記憶疊圖：開",
"Memory overlay: off": "記憶疊圖：關",
"◀ <b>left hemisphere</b> {n} neurons": "◀ <b>左半腦</b> {n} 個神經元",
"{n} neurons <b>right hemisphere</b> ▶": "{n} 個神經元 <b>右半腦</b> ▶",
"Dim = silent, bright = spiking on this timestep.": "暗 = 靜止，亮 = 在這個時間步發放脈衝。",
"every line is a traced neurite; firing changes brightness, never thickness": "每條線都是一段追蹤重建的神經突；發放只改變亮度，不改變粗細",
"atlas redraw {ms}": "圖譜重繪 {ms}",
"▶ replay game": "▶ 重播棋局",
"■ stop": "■ 停止",
"live": "即時",
"live · t={t}": "即時・t={t}",
"Continuous activity across the game": "整盤棋的連續活動",
"state carried, never reset": "狀態延續，從不重設",
"neurons firing now": "目前發放中的神經元",
"of {H}": "共 {H} 個",
"{n} of {H}": "{n}／{H}",
"carried from previous move": "延續自上一步",
"spike overlap": "脈衝重疊",
"still shared with move 1": "仍與第 1 步相同",
"unbroken state trajectory": "未中斷的狀態軌跡",
"cost per timestep": "每個時間步的耗時",
"constant — O(H) state": "固定：O(H) 狀態",
"The lower trace is wall-clock cost per timestep in your browser. It stays <b>flat</b> as the game grows because the circuit carries its state instead of re-reading the game — the readout at move 40 costs exactly what move 1 cost.": "下方曲線是你的瀏覽器中每個時間步的實際耗時。隨著棋局進行它保持<b>平坦</b>，因為迴路延續自己的狀態，而不是把整盤棋重新讀一次：第 40 步的讀出和第 1 步花的時間一樣。",
"Firing rate per cell class": "各細胞類別的發放率",
"waiting": "等待中",
"no move computed yet": "尚未計算任何棋步",
"The <b>mushroom body</b> is the fly's olfactory <i>learning</i> centre. Four cell classes do the work, and all four are drawn on the atlas:": "<b>蘑菇體</b>是果蠅的嗅覺<i>學習</i>中樞。四類細胞各司其職，全都畫在圖譜上：",
"Kenyon cells": "Kenyon cell（KC）",
"Sparse expansion layer: the <b>keys</b>. Dendrites in the <b>calyx</b>, axons down the <b>peduncle</b> into the α/β, α'/β' and γ <b>lobes</b>.": "稀疏的擴展層，也就是<b>索引鍵</b>。樹突位於<b>萼部</b>，軸突沿著<b>柄部</b>延伸到 α/β、α'/β' 與 γ <b>葉</b>。",
"MBONs": "輸出神經元（MBON）",
"Output neurons carrying learned <b>values</b>. Their dendrites tile the lobes into compartments; everything downstream sees only these.": "帶著學到的<b>價值</b>的輸出神經元。它們的樹突把各葉分成一個個隔區；下游只看得到它們。",
"DANs": "多巴胺神經元（DAN）",
"Dopamine. They <b>gate the write</b> onto KC→MBON synapses. PAM cells innervate the medial lobes, PPL1 cells the vertical lobes.": "多巴胺。它們<b>調控寫入</b> KC→MBON 突觸。PAM 細胞支配內側葉，PPL1 細胞支配垂直葉。",
"One giant GABAergic neuron per hemisphere, spanning the whole structure. Global <b>inhibitory feedback</b> that keeps the KC code sparse.": "每側一個巨大的 GABA 能神經元，遍布整個結構。它提供全域的<b>抑制性回饋</b>，讓 KC 的編碼保持稀疏。",
"Connectome and soma coordinates: <b>MaleCNS v1.0</b> (male <i>Drosophila melanogaster</i> central nervous system), used under <b>CC-BY-4.0</b>. Excitatory/inhibitory signs from the release's neurotransmitter annotations; Kenyon cells are treated as cholinergic (excitatory). 4,510 neurons, 1,027,152 within-MB neuron-to-neuron connections, {cross} of them crossing the midline. Neuron morphology from the same release's traced skeletons.": "連結體與細胞體座標：<b>MaleCNS v1.0</b>（雄性<i>黑腹果蠅</i>中樞神經系統），依 <b>CC-BY-4.0</b> 授權使用。興奮／抑制符號取自該版資料的神經傳導物質標註；Kenyon cell 視為膽鹼性（興奮性）。4,510 個神經元、1,027,152 條蘑菇體內神經元之間的連結，其中 {cross} 條跨越中線。神經元形態取自同一版資料的追蹤骨架。",
"Connectome and soma coordinates: <b>MaleCNS v1.0</b> (male <i>Drosophila melanogaster</i> central nervous system), used under <b>CC-BY-4.0</b>. Excitatory/inhibitory signs from the release's predicted neurotransmitters. {H} neurons, {E} within-region neuron-to-neuron connections{cross}. Neuron morphology from the same release's traced skeletons.": "連結體與細胞體座標：<b>MaleCNS v1.0</b>（雄性<i>黑腹果蠅</i>中樞神經系統），依 <b>CC-BY-4.0</b> 授權使用。興奮／抑制符號取自該版資料預測的神經傳導物質。{H} 個神經元、{E} 條此腦區內神經元之間的連結{cross}。神經元形態取自同一版資料的追蹤骨架。",
", {n} of them crossing the midline": "，其中 {n} 條跨越中線",
"The circuit you are watching": "你正在觀看的迴路",
"The machine": "運算細節",
"loading…": "載入中…",
"dorsal projection · x = medial-lateral, z = anterior-posterior": "背面投影・x = 內外側，z = 前後",
"frontal projection · x = medial-lateral, y = dorsal-ventral": "正面投影・x = 內外側，y = 背腹",
"{n} spiking": "{n} 個發放中",
"L {l} / R {r}": "左 {l}／右 {r}",
"{n} ms": "{n} 毫秒",
"carried from move 1": "延續自第 1 步",
"timestep (one per move) →": "時間步（每步棋一個）→",
"ms / timestep": "毫秒／時間步",
"timestep →": "時間步 →",
"first {a} · last {b} ms": "第一步 {a}・最近 {b} 毫秒",
"This browser cannot run the fly": "這個瀏覽器無法執行果蠅",
"Missing: <b>{list}</b>. Please use a current Chrome, Edge, Firefox (114+) or Safari (15+).": "缺少：<b>{list}</b>。請使用新版的 Chrome、Edge、Firefox（114 以上）或 Safari（15 以上）。",
"The engine failed to start": "引擎無法啟動",
"Weights location not configured": "尚未設定權重位置",
"Set <b>WEIGHTS_BASE</b> for this model in <code>config.js</code> to the model folder URL (e.g. the Hugging Face <code>resolve/main/</code> URL).": "請在 <code>config.js</code> 中為這個模型設定 <b>WEIGHTS_BASE</b>，指向模型資料夾的網址（例如 Hugging Face 的 <code>resolve/main/</code> 網址）。",
"the fly's {region}": "果蠅的{region}",
"the fly's brain": "果蠅的腦",
"Loading {brain}…": "正在載入{brain}…",
"Downloading the trained connectome weights. Everything runs locally in this tab.": "正在下載訓練好的連結體權重。所有運算都在這個分頁中於本機進行。",
"starting…": "準備中…",
"building the network": "建構網路中",
"Could not load {brain}": "無法載入{brain}",
"PASS": "通過",
"FAIL": "未通過",
"connectome": "連結體",
"MaleCNS v1.0 {region} (CC-BY-4.0)": "MaleCNS v1.0 {region}（CC-BY-4.0）",
"neurons": "神經元",
"neuron-to-neuron connections": "神經元之間的連結",
"Dale signs": "戴爾原則符號",
"E {E} / I {I} / modulatory {mod}": "興奮 {E}／抑制 {I}／調節 {mod}",
"hemispheres": "左右半腦",
"{L} L / {R} R": "左 {L}／右 {R}",
"soma coordinates": "細胞體座標",
"{a} measured, {b} imputed": "實測 {a}、推估 {b}",
"unavailable": "無法取得",
"run mode": "執行模式",
"RSNN (one timestep per move, state carried, no reset) · in this browser tab": "RSNN（每步棋一個時間步，狀態延續、不重設）・在這個瀏覽器分頁中執行",
"input → readout": "輸入 → 讀出",
"{nin} {input} → {nout} {output} (no dopamine gate)": "{nin} 個{input} → {nout} 個{output}（沒有多巴胺閘門）",
"synaptic weights": "突觸權重",
"trained with <a href=\"https://arxiv.org/abs/2604.01295\" target=\"_blank\" rel=\"noopener\">PHCSSM</a> parallel-scan mode, deployment in sequential RSNN mode": "以 <a href=\"https://arxiv.org/abs/2604.01295\" target=\"_blank\" rel=\"noopener\">PHCSSM</a> 平行掃描模式訓練，以序列 RSNN 模式部署",
"move vocabulary": "棋步詞彙",
"trained parameters": "訓練參數",
"{x} M": "{x} 百萬",
"model": "模型",
"weights in this page": "本頁使用的權重",
"{variant} · {mb} MB loaded from this browser's storage": "{variant}・{mb} MB，從這個瀏覽器的儲存空間載入",
"{variant} · {mb} MB loaded ({net} MB downloaded, the rest from this browser's storage)": "{variant}・{mb} MB（下載 {net} MB，其餘從這個瀏覽器的儲存空間載入）",
"{variant} · {mb} MB downloaded, kept in this browser for next time": "{variant}・已下載 {mb} MB，並保存在這個瀏覽器中供下次使用",
"{variant} · {mb} MB downloaded": "{variant}・已下載 {mb} MB",
"recurrent weights": "遞迴權重",
"{n} nonzero, {m} off the connectome": "{n} 個非零，{m} 個在連結體之外",
"Dale check": "戴爾原則檢查",
"{n} wrong-sign weights": "{n} 個符號錯誤的權重",
"engine vs reference": "引擎與參考實作比對",
"legal top-1 {a}/{b} vs the fp32 reference ({n} {games}); {x} of {y} spike bits differ from the reference on the same weights": "合法棋步中的第一選擇與 fp32 參考實作一致 {a}/{b}（{n} 盤{games}）；使用相同權重時，{x}／{y} 個脈衝位元與參考實作不同",
"held-out games": "保留對局",
"fly-vs-fly reference games": "果蠅對果蠅參考對局",
"load-time self-check": "載入時自我檢查",
"— legal top-1 {a}/{b} plies, max |Δlogit| {e}": "— 合法棋步第一選擇一致 {a}/{b} 手，最大 |Δlogit| {e}",
"engine load": "引擎載入時間",
"{s} s": "{s} 秒",
"Model: {label} ({variant} weights).": "模型：{label}（{variant} 權重）。",
"strength": "棋力",
"{a} of {b}": "{a}／{b}",
"Bilateral: <b>{L} left / {R} right</b>, and <b>{p}%</b> of {edges} cross the midline — the two sides are not independent copies.": "左右對稱：<b>左 {L}／右 {R}</b>，其中 <b>{p}%</b> 的{edges}跨越中線：左右兩側並不是彼此獨立的複本。",
"edges": "連結",
"edges between neurons of known side": "已知左右側神經元之間的連結",
"{n} traced cells · {b} branches · MaleCNS v1.0": "{n} 個追蹤重建的細胞・{b} 個分支・MaleCNS v1.0",
"Every line is a real traced neuron. Dim = silent; when a neuron spikes its WHOLE cell lights up.": "每條線都是一個真實追蹤重建的神經元。暗 = 靜止；神經元發放脈衝時，整個細胞都會亮起。",
"{n} cells have no published skeleton.": "有 {n} 個細胞沒有公開的骨架資料。",
"MaleCNS v1.0 skeletons-malecns/skeletons-precomputed (CC-BY-4.0)": "MaleCNS v1.0 預先計算的神經元骨架（CC-BY-4.0）",
"{n} measured soma positions (skeletons unavailable)": "{n} 個實測細胞體位置（無法取得骨架）",
"Skeletons could not be loaded — falling back to measured soma positions (one dot per neuron).": "無法載入骨架，改用實測的細胞體位置（每個神經元一個點）。",
"fly:": "果蠅：",
"fly error": "果蠅出錯",
"fly error: {msg}": "果蠅出錯：{msg}",
"stay": "不動",
"up": "往上",
"down": "往下",
"Still training — not available yet": "仍在訓練中，暫時無法使用",
"Record: {s}": "戰績：{s}",
"The fly's paddle is moved by a spiking network wired from the <b>real MaleCNS {name} connectome</b> — {H} measured neurons, {E} neuron-to-neuron connections, excitatory/inhibitory signs from neurotransmitter annotations. It sees six numbers each frame (the ball's position and velocity and both paddles) and answers stay, up or down. The network takes <b>one timestep per frame</b>, 60 frames per second, and its state is never reset during a game. It learned by copying the actions of a scripted Pong player. The whole network runs <b>in your browser</b> (a Web Worker) — no server computes anything.": "果蠅的球拍由一個脈衝神經網路移動，它依<b>真實的 MaleCNS {name}連結體</b>接線：{H} 個實測神經元、{E} 條神經元之間的連結，興奮／抑制符號取自神經傳導物質標註。它每一幀看到六個數字（球的位置與速度，以及兩邊球拍的位置），回答不動、往上或往下。網路<b>每一幀走一個時間步</b>，每秒 60 幀，一局之中狀態從不重設。它是模仿一個程式化 Pong 玩家的動作學會的。整個網路都<b>在你的瀏覽器中</b>執行（Web Worker），沒有任何伺服器參與運算。",
"The fly wins {a}–{b}.": "果蠅以 {a}–{b} 獲勝。",
"You win {a}–{b}.": "你以 {a}–{b} 獲勝。",
"Paused. Press Start or Space to continue.": "已暫停。按「開始」或空白鍵繼續。",
"Press Start or Space to serve.": "按「開始」或空白鍵發球。",
"The fly scores.": "果蠅得分。",
"You score.": "你得分。",
"fly: {ms} ms per timestep": "果蠅：每個時間步 {ms} 毫秒",
"fly: {ms} ms per timestep · {fps} frames per second": "果蠅：每個時間步 {ms} 毫秒・每秒 {fps} 幀",
"slower than real time on this device: every frame is still simulated, none is skipped": "在這台裝置上比即時慢：每一幀仍然都有模擬，沒有跳過任何一幀",
"Pause": "暫停",
"Start": "開始",
"<b>The fly wins {a}–{b}.</b> Press New game for a rematch.": "<b>果蠅以 {a}–{b} 獲勝。</b>按「新的一局」再比一場。",
"<b>You win {a}–{b}.</b> Press New game to play again.": "<b>你以 {a}–{b} 獲勝。</b>按「新的一局」再玩一次。",
"{n} actions (stay, up, down)": "{n} 種動作（不動、往上、往下）",
"<b>Honest caveat.</b> This fly learned by copying a scripted Pong player: it gets no reward, plans nothing ahead and has no model of the game beyond what its trained wiring computes from the six numbers it sees.": "<b>老實說明。</b>這隻果蠅是模仿一個程式化 Pong 玩家學會的：它沒有獎賞、不做任何事先規劃，除了訓練過的接線從它看到的六個數字算出的東西之外，它對這個遊戲沒有別的模型。",
"Each paddle command is one timestep of the network. The interesting claim is <i>which substrate is computing</i>.": "每一個球拍指令都只是網路的一個時間步。真正有意思的是<i>究竟是什麼基質在計算</i>。",
"carried from previous frame": "延續自上一幀",
"still shared with frame 1": "仍與第 1 幀共享",
"The lower trace is wall-clock cost per timestep in your browser, one timestep per frame. It stays <b>flat</b> because the circuit carries its state instead of re-reading the game: frame 3,000 costs exactly what frame 1 cost. The charts show the last 900 frames.": "下方曲線是你的瀏覽器中每個時間步的實際耗時，每一幀一個時間步。它保持<b>平坦</b>，因為迴路延續自己的狀態，而不是把整局重新讀一次：第 3,000 幀花的時間和第 1 幀一樣。圖表顯示最近 900 幀。",
"carried from frame 1": "延續自第 1 幀",
"timestep (one per frame) →": "時間步（每幀一個）→",
"{x} of {y} spike bits differ from the reference on the same weights ({a} held-out frames and a {b}-frame closed-loop game)": "使用相同權重時，{x}／{y} 個脈衝位元與參考實作不同（{a} 個保留測試幀，以及一場 {b} 幀的閉環對局）",
"RSNN (one timestep per frame at 60 frames per second, state carried through the game) · in this browser tab": "RSNN（每秒 60 幀、每幀一個時間步，狀態在整局中延續）・在這個瀏覽器分頁中執行",
"actions": "動作",
"— top-1 {a}/{b} frames, max |Δlogit| {e}": "— 第一選擇一致 {a}/{b} 幀，最大 |Δlogit| {e}",
"Rally hits: {n}": "本回合擊球：{n} 次",
"record": "戰績",
"{n} of the {m} spiking cells are drawn each frame, rotating, so the game keeps real time": "每一幀從 {m} 個發放的細胞中輪流畫出 {n} 個，好讓遊戲維持即時"
};
